version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: sporta-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: sporta
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    container_name: sporta-redis
    restart: unless-stopped
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data
    command: ['redis-server', '--requirepass', 'sporta']
    environment:
      REDIS_PASSWORD: sporta

volumes:
  postgres_data:
  redis_data:
